import type { EditorialStatus } from "./content";
import type { PublicDocument } from "./documents";

/**
 * Generated by scripts/sync-dropbox-public-feed.mjs.
 *
 * The committed empty state is intentional: Dropbox must provide an explicit,
 * approved manifest before any automated item enters the website.
 */
export type DropboxFeedItem = {
  id: string;
  kind: "research" | "documentary" | "video" | "series";
  title: string;
  category: string;
  description: string;
  status: EditorialStatus;
  readingTime?: string;
};

export type DropboxDocumentItem = PublicDocument;

export const dropboxFeedItems: DropboxFeedItem[] = [];
export const dropboxDocumentItems: DropboxDocumentItem[] = [];
