import type { EditorialStatus } from "./content";

/**
 * Generated by scripts/sync-dropbox-public-feed.mjs.
 *
 * The committed empty state is intentional: Dropbox must provide an explicit,
 * approved manifest before any automated item enters the website.
 */
export type DropboxFeedItem = {
  id: string;
  kind: "research" | "documentary" | "video" | "series";
  title: string;
  category: string;
  description: string;
  status: EditorialStatus;
  readingTime?: string;
};

export const dropboxFeedItems: DropboxFeedItem[] = [];
