name: Dependency review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Review dependency changes
        # v4.6.0
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5b8a807627bf8
